### ISSUE TITLE
Error searching for japanese artist

### ISSUE THREAD

**Issue by tmatzxzone** [slonopot/Beenius#2]
Can you add romanized lyrics for japanese artist too?

```2022/11/26 07:50:14.823 | Info | Beenius.GeniusClient..ctor | No configuration file was provided, defaults were used
2022/11/26 07:50:17.871 | Info | Beenius.GeniusClient.getLyrics | Attempting to search for "さユり" - "酸欠少女"
2022/11/26 07:50:17.887 | Debug | Beenius.GeniusClient.search | artist="さユり", title="酸欠少女"
2022/11/26 07:50:18.650 | Info | Beenius.GeniusClient.search | Let's check for aliases
2022/11/26 07:50:19.535 | Info | Beenius.GeniusClient.search | No aliases
2022/11/26 07:50:19.542 | Info | Beenius.GeniusClient.search | No results for this search
2022/11/26 07:50:19.542 | Info | Beenius.GeniusClient.getLyrics | Nothing found at all ```

**Comment by slonopot** [comment]
This query should probably hit [this](https://genius.com/Sayuri-sanketsu-girl-lyrics) if you set delimiters=["("] and trimTitle=true. Then, there are [romanizations](https://genius.com/Genius-romanizations-sayuri-mikazuki-romanized-lyrics) available separately for さユり and if that's what you need then I'll have to think how can I manage to do this. For さユり - ミカヅキ you can try to set allowedDistance=50 and see if it will get you a romanized version since it's the first one in the search results.

Additionally, lyrics in Japanese seems to be available in Musixmatch without any additional conversions, you can try my other addon and see if it fits you.

**Comment by slonopot** [comment]
Now that I think about it, one of the options could be to add [something like this](https://github.com/Cutano/Kawazu), check if the text is in Japanese and romanize it automatically. I'm still not sure if it's necessary to add it to the build since the thing is very specific.
