### ISSUE TITLE
No logging when playing a song without lyrics

### ISSUE THREAD

**Issue by lamrongol** [slonopot/Beenius#3]
I've installed this plugin and play a song without lyrics but no lyrics is gotten.
I checked %APPDATA%\MusicBee\beenius.log but there is only one line:
> 2022/11/28 09:31:31.339 | Info | Beenius.GeniusClient..ctor | No configuration file was provided, defaults were used

I tried to solve this problem and cloned repository and opened in Visual Studio 2022, ". NET 5.0 Runtime (Out of support)" is required.

**Comment by slonopot** [comment]
Yeah, there's an issue with the logger configuration. Since MusicBee launches all the plugins in the same context, global logger settings are being overriden by the last launched plugin and that's why if there are both Beenius and Museexmatch installed the logs are being pushed to either of the log files. I'm not sure why logging is that important and as far as I can remember I've tried to fix the issue in the latest build with zero luck. I'm too lazy to take this just for logging, maybe one day the plugins will require a bump and I'll certainly devote my time to working on it, but for now ``(´,_ゝ`)``
