### ISSUE TITLE
Suggestion for a new lyrics plugin for Bandcamp?

### ISSUE THREAD

**Issue by sveakul** [slonopot/Beenius#4]
Both your Beenius and Museexmatch lyrics plugins work so well in MusicBee that I was hoping you might consider adding Bandcamp if it can be done.  This is due to the fact that they receive lyrics directly from the artists and labels and often feature newly released material.  My apologies if I should be posting this request elsewhere.  Thanks for your consideration.

**Comment by slonopot** [comment]
I just got me a Bandcamp app installed and the lyrics are nowhere to be found. Don't you have any screenshot or example of the lyrics you're talking about? If I'm not mistaken, the lyrics must be embedded into the file you get from Bandcamp and these must appear in MusicBee automatically, but I'll take another look when I see any particular piece with lyrics

**Comment by sveakul** [comment]
The Bandcamp website lyrics appear next to the track listing of a band's album.  For example, check [https://deltasleep.bandcamp.com/album/spring-island?from=discover-top](url) ; if you mouse down the track list halfway down the page, you see a "Lyrics" link appear to the right of the title, which when clicked displays the lyrics.

A working implementation exists in the AIMP player using the code addition to its plugin's *.ini which was posted [here](https://www-aimp-ru.translate.goog/forum/index.php?PHPSESSID=51e43458c4b7cc51f6043abb770cc3c1&topic=57148.msg431855&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp#msg431855) (the lyrics addition is the first segment only).

**Comment by slonopot** [comment]
Lyrics are not present in the mobile app. They have a "[has_lyrics](https://bandcamp.com/api/mobile/25/tralbum_details?band_id=2228040235&tralbum_id=3548736953&tralbum_type=a)" flag but lyrics themselves are nowhere to be found.

![image](https://github.com/slonopot/Beenius/assets/74996144/1ab522ea-706b-44d0-bf1f-343d9f9ee8dd)

You may try and drop them a message like you absolutely require the lyrics to be present in their mobile app. It will take them around an hour or two total to sort this out and then I'll be able to create a decent plugin.

As for the web version, their website is looking like that for over 5 years now and it's probably safe to say that there are no incoming redesigns. Maybe a parser for LyricsReloaded will suffice, maybe manually moving those to Genius is an option (it's the first time I see the lyrics on Bandcamp though). I won't be supporting web version in any way and the main reason behind this decision is that LyricsReloaded thread has 20+ pages of hella active discussions and regex tweakings and mine are dead stable because I only rely on APIs and these don't get changed very often. There's a certain probablility that later these dudes at Bandcamp would decide that they can't survive without a DDoS protection, they might incorporate a Cloudflare challenge or some Akamai Bot Protection trash which will render my plugin unusable.

**Comment by slonopot** [comment]
Btw they've already started working on implementing the lyrics into their app, all they need is to actually return them from the server.

![image](https://github.com/slonopot/Beenius/assets/74996144/33da67e9-cb99-46ad-933a-339addb333d3)

**Comment by sveakul** [comment]
Thanks for the heads-up, that's a good sign for the future!
